"""empty message

Revision ID: c3150df1ebea
Revises: 
Create Date: 2024-10-02 12:07:35.131964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3150df1ebea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_product_id', sa.String(), nullable=True),
    sa.Column('exchange_product_name', sa.String(), nullable=True),
    sa.Column('oil_id', sa.String(), nullable=True),
    sa.Column('delivery_basis_id', sa.String(), nullable=True),
    sa.Column('delivery_basis_name', sa.String(), nullable=True),
    sa.Column('delivery_type_id', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_result')
    # ### end Alembic commands ###
